stages:
  - info
  - lint
  - test

ENV info:
  stage: info
  tags:
    - mac-ventura-preview
  script:
    - system_profiler SPSoftwareDataType # system info
    - xcodebuild -version
    - xcode-select -p # default Xcode version
    - ls /Applications/ | grep Xcode # other Xcodes
    - xcbeautify --version
    - swiftlint --version
    - carthage version
    - gh --version
    - brew -v
    - bundler --version
    - python3 -V

Lint:
  stage: lint
  tags:
    - mac-ventura-preview
  script:
    - ./tools/lint/run-linter.sh
    - ./tools/license/check-license.sh

# SDK unit tests:
#   stage: test
#   tags:
#     - mac-ventura-preview
#   variables:
#     TEST_WORKSPACE: "Datadog.xcworkspace"
#     TEST_PLATFORM: "iOS Simulator"
#     TEST_DEVICE_NAME: "iPhone 15,OS=17.0.1"
#   script:
#     - carthage bootstrap --platform iOS,tvOS --use-xcframeworks
#     - make source-xcconfigs
#     - xcodebuild -workspace '$TEST_WORKSPACE' -scheme 'DatadogCore iOS' -showdestinations
#     - xcodebuild -workspace '$TEST_WORKSPACE' -scheme '$TEST_SCHEME' -destination 'platform=$TEST_PLATFORM,name=$TEST_DEVICE_NAME' test | xcbeautify

# SDK integration tests:
#   stage: test
#   tags:
#     - mac-ventura-preview
#   script:
#     - make prepare-integration-tests
#     - ./tools/config/generate-http-server-mock-config.sh
#     - xcodebuild -workspace IntegrationTests/IntegrationTests.xcworkspace -scheme "IntegrationScenarios" -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0.1' -testPlan DatadogIntegrationTests test | xcbeautify
#     # We suspect Apple Crash Reporter causing flakiness in our CR integration tests, so we disable it.
#     # It makes the system prompt ("Example iOS quit unexpectedly") not appear:
#     - launchctl unload -w /System/Library/LaunchAgents/com.apple.ReportCrash.plist
#     - xcodebuild -workspace IntegrationTests/IntegrationTests.xcworkspace -scheme "IntegrationScenarios" -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0.1' -testPlan DatadogCrashReportingIntegrationTests test | xcbeautify

# SDK smoke tests:
#   stage: test
#   tags:
#     - mac-ventura-preview
#   script:
#     - brew install xcbeautify
#     - make test-spm ci=1
#     - xcodebuild -project dependency-manager-tests/spm/SPMProject.xcodeproj -scheme "App iOS" -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0.1' test | xcbeautify

# Swift tools tests:
#   stage: test
#   tags:
#     - mac-ventura-preview
#   script: 
#     - swift test --package-path instrumented-tests/http-server-mock
#     - swift test --package-path tools/rum-models-generator
#     - swift test --package-path tools/sr-snapshots

# Python tools tests:
#   stage: test
#   tags:
#     - mac-ventura-preview
#   script:
#     - |
#       cd tools/distribution && make
#       venv/bin/python3 -m pytest tests
#     - |
#       cd tools/nightly-unit-tests && make
#       venv/bin/python3 -m pytest tests